services:
  order-service:
    build:
      context: ./packages/order-service
    ports:
      - "3000:3000"

  order-processing-service:
    build:
      context: ./packages/order-processing-service
    ports:
      - "3001:3001"

  inventory-service:
    build:
      context: ./packages/inventory-service
    ports:
      - "3002:3002"

  kafka:
    image: wurstmeister/kafka:latest
    ports:
      - "9092:9092"  # Port for external access (OUTSIDE)
      - "9093:9093"  # Additional port for INSIDE access
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9093,OUTSIDE://localhost:9092  # Change to match the new port
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9093,OUTSIDE://0.0.0.0:9092  # Update ports here as well
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_MESSAGE_MAX_BYTES: 200000000  # 200 MB
      KAFKA_REPLICA_FETCH_MAX_BYTES: 200000000  # 200 MB
      KAFKA_FETCH_MESSAGE_MAX_BYTES: 200000000  # 200 MB
  
  zookeeper:
    image: wurstmeister/zookeeper:latest
    ports:
      - "2181:2181"
